### ISSUE TITLE
Internal Server Error on Upload

### ISSUE THREAD

**Issue by ghost** [dpnishant/raptor#11]
I git cloned raptor, then cd into the directory and then started with "sudo sh install.sh";
No problem at installation;
Then i type "sudo sh start.sh"
and went with firefox on localhost/raptor;
I logged in, but when i try to upload a zipped/rar source code, it give me Interal Server Error without any other infos or anything;
Any ideas?

**Comment by ghost** [comment]
Update, without using sudo it work, "sh start.sh"; I don't know why, that's strange;
I will not close issues at the moment for updates!

**Comment by dpnishant** [comment]
@H0nus  Not sure about it. As I tried to reproduce the issue on Ubuntu 16.04 and 14.04, I do not see any such issue.

**Comment by dpnishant** [comment]
Re-open once you have more details to reproduce the issue.
