### ISSUE TITLE
commandline version please

### ISSUE THREAD

**Issue by anantshri** [dpnishant/raptor#2]
provide a version which works via commandline.

**Comment by dpnishant** [comment]
you can simply run the backend web-service and use a tool like wget or curl to immediately start using Raptor via command-line. Let me know if that solves your purpose or you need a true command-line version?

**Comment by anantshri** [comment]
Can you provide a sample commandset for running it via webservices and not UI.

**Comment by dpnishant** [comment]
https://github.com/dpnishant/raptor/blob/master/backend/server.py#L16-L18
