### ISSUE TITLE
Broken href link for Raptor: Source Code Scanner header

### ISSUE THREAD

**Issue by sanjogpandasp** [dpnishant/raptor#5]
Hi,

You might like to change the href link of "Raptor: Source Code Scanner" header on the home page from href ="/" to href="/raptor/".

![2016-01-27 11_40_17-raptor_ source code scanner](https://cloud.githubusercontent.com/assets/5404943/12605542/f5bb960c-c4eb-11e5-909b-62d7b2c64301.png)

**Comment by dpnishant** [comment]
Thanks @sanjogpandasp for finding this. Have fixed in fecef98a03cc5c383977bcaaf6d58b31ea2c957e
