### ISSUE TITLE
[FIXED] Ubuntu Kylin (16.04) Bug

### ISSUE THREAD

**Issue by dpnishant** [dpnishant/raptor#6]
![13225054_10209304188660655_1001771138_o](https://cloud.githubusercontent.com/assets/1339669/15405321/3bd637b4-1db6-11e6-978a-246781a85752.png)

If you face such an error while trying to run Raptor on Ubuntu Kylin (16.04) you may follow the steps below to resolve the issue, hopefully:
1. Clone a fresh copy of the repository with `git clone https://dpnishant/raptor` OR pull the latest changes to your local repository by running `git pull origin master`
2. Download the Installer patch file from the [Gist here](https://gist.github.com/dpnishant/9afaa7916cf2ae2de548c6b2382be94e)
3. Apply the patch by running `patch install.sh -i raptor_kylin_install.patch -o install_kylin.sh`
4. Execute the installer script by running `sudo -H sh install_kylin.sh`
5. After that follow the instructions on [README.md](https://github.com/dpnishant/raptor/blob/master/README.md) as normal.

If you still face any other error, feel free to open new issues.

CREDIT: I would like to thank Prajal Kulkarni (@prajal) for reporting this issue to me.

**Comment by prajal** [comment]
Yup this works! Thanks

**Comment by dpnishant** [comment]
Thanks for the confirmation @prajal! Closing.

**Comment by xiaofengtongxue** [comment]
Error is always Service Unavailable

**Comment by dpnishant** [comment]
@xiaofengtongxue Did you follow [these instructions](https://github.com/dpnishant/raptor#usage)?

**Comment by Shazgul** [comment]
"patch install.sh -i raptor_kylin_install.patch -o install_kylin.sh
patching file install_kylin.sh (read from install.sh)
patch unexpectedly ends in middle of line
patch: **** unexpected end of file in patch at line 42"

**Comment by dpnishant** [comment]
Hi @Shazgul,

Updated the patch file https://gist.github.com/dpnishant/9afaa7916cf2ae2de548c6b2382be94e. Try patching it again and run the install script.
