### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by binb4sh** [dpnishant/raptor#7]
Service Unavailable
Please contact your server administrator.

**Comment by Shazgul** [comment]
Same problem here, and yes i typed "sudo sh start.sh"

**Comment by dpnishant** [comment]
Can you please paste your terminal output about what error do you see when you run 'sudo sh start.sh'? Probably you should re-run the install.sh script and make sure nothing fails to install.

**Comment by dpnishant** [comment]
No response. Closing
