### ISSUE TITLE
Unable to start the backend webservice

### ISSUE THREAD

**Issue by kondurujashwanth** [dpnishant/raptor#9]
Hi,

I am unable to start the backend web service due to gunicorn .Can you please help me how to resolve the issue.
![screenshot from 2017-02-07 14 48 44](https://cloud.githubusercontent.com/assets/16999749/22685654/27fd0f18-ed47-11e6-8808-7664bda70600.png)

**Comment by kondurujashwanth** [comment]
While installing i am getting trace back error .
![screenshot from 2017-02-07 14 51 25](https://cloud.githubusercontent.com/assets/16999749/22685710/62a88c14-ed47-11e6-8caa-05f331b8c91b.png)

**Comment by shengulong** [comment]
I come with tht same problem as @kondurujashwanth

**Comment by dpnishant** [comment]
gunicorn python module is either not installed or is installed in a location which is not in the `$PATH` env var. Re-run `sudo -H install.sh` to fix that issue.
